# Generated by Django 3.0.1 on 2020-05-10 09:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveGameMatch',
        ),
        migrations.AddField(
            model_name='activegame',
            name='blackPlayer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activegame',
            name='gameMoves',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=[], size=None),
        ),
        migrations.AddField(
            model_name='activegame',
            name='whitePlayer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
