# Generated by Django 3.0.1 on 2020-05-10 09:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200510_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activegame',
            name='gameMoves',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=list, size=None),
        ),
    ]
